import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import HomePage from '../components/Homepage/index.js'

export default function Home () {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home - Doctor Booking System</title>
        <meta name='description' content='Generated by create next app' />
        <link
          rel='icon'
          href='https://doccure-wp.dreamguystech.com/wp-content/uploads/2021/10/favicon.png'
        />
      </Head>
      <HomePage />
    </div>
  )
}
